"""Turkce yardimci listeler (duygu, zamir, dolgu). Genisletilebilir."""

from __future__ import annotations

FIRST_PERSON_PRONOUNS_TR = frozenset(
    {
        "ben",
        "bana",
        "benden",
        "banaydı",
        "beni",
        "benim",
        "benimle",
        "bence",
        "kendim",
        "kendimi",
        "kendime",
        "kendimden",
        "kendimle",
        "biz",
        "bize",
        "bizden",
        "bizi",
        "bizim",
        "bizimle",
    }
)

FILLERS_TR = frozenset(
    {
        "eee",
        "ııı",
        "ıı",
        "şey",
        "yani",
        "işte",
        "hani",
        "aslında",
        "falan",
        "filan",
        "mesela",
        "bir",
        "neydi",
        "neyse",
        "valla",
        "walla",
        "yok",
        "şimdi",
        "biraz",
        "galiba",
        "sanki",
        "tabii",
        "tabi",
        "anladın",
        "anlarsın",
        "diyeyim",
        "desem",
        "diye",
    }
)

NEGATIVE_WORDS_TR = frozenset(
    {
        "kötü",
        "berbat",
        "umutsuz",
        "umutsuzluk",
        "yorgun",
        "yorgunluk",
        "bitkin",
        "tükenmiş",
        "tükenmişlik",
        "sıkıntı",
        "sıkıntılı",
        "stres",
        "stresli",
        "endişe",
        "kaygı",
        "kaygılı",
        "korku",
        "değersiz",
        "değersizlik",
        "yalnız",
        "yalnızlık",
        "mutsuz",
        "mutsuzluk",
        "üzgün",
        "üzüntü",
        "depresyon",
        "depresif",
        "isteksiz",
        "bunalım",
        "uykusuz",
        "uyuyamıyorum",
        "iştahsız",
        "intihar",
        "yapamıyorum",
        "dayanamıyorum",
        "zor",
        "zorlanıyorum",
        "mobbing",
        "yıprandım",
        "yıpranıyorum",
    }
)

POSITIVE_WORDS_TR = frozenset(
    {
        "iyi",
        "güzel",
        "harika",
        "mutlu",
        "mutluluk",
        "keyif",
        "keyifli",
        "huzurlu",
        "huzur",
        "rahat",
        "sevindim",
        "başarı",
        "umut",
        "umutlu",
        "teşekkür",
        "sağlıklı",
        "enerjik",
        "sevgi",
        "destek",
        "güven",
        "olumlu",
        "pozitif",
    }
)

PAST_SUFFIX_HINTS = (
    "di",
    "dı",
    "du",
    "dü",
    "miş",
    "muş",
    "müş",
    "mış",
    "ydi",
    "ydı",
    "idi",
    "dim",
    "dım",
    "dum",
    "düm",
)

FUTURE_SUFFIX_HINTS = ("ecek", "acak", "eceğim", "acağım", "eceksin", "acaksın")
