[supervisord]
nodaemon=true
logfile=/dev/null
pidfile=/tmp/supervisord.pid

[program:text-to-sentiment]
directory=/app
command=python /app/text_to_sentiment/app.py
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:voice-to-text]
directory=/app
command=python /app/voice_to_text/app.py
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:voice-to-sentiment]
directory=/app
environment=AUDIO_SENTIMENT_CKPT="/app/models/wavlm_v6_multicrop_ema_best.pt"
command=python /app/voice_to_sentiment/app.py
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:fusion-service]
directory=/app
command=python /app/fusion_service/app.py
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:disease-service]
directory=/app
command=python /app/disease_service/app.py
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:mental-fitness]
directory=/app
environment=MENTAL_FITNESS_MODEL_PATH="/app/models/extratreesclassifier.joblib"
command=python /app/mental_fitness/app.py
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
